version: '2.4'
services:
  app:
    build: .
    env_file:
      - config.env
    ports:
      - "8008:5321"
    cpus: 1
    pids_limit: 256
    mem_limit: 512m
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped

