global:
  scrape_interval: 10s
scrape_configs:
  - job_name: "apps"
    static_configs:
      - targets: ["app-instance-1"]
        labels:
          instance: "1"
      - targets: ["app-instance-2"]
        labels:
          instance: "2"
