version: "2.4"

services:
  app-instance-1: &app
    image: ptzctf/uptime/app
    build: ./app
    expose:
      - 80
    ports:
      - 80
    networks:
      - internal
    restart: unless-stopped
    pids_limit: 64
    cpus: 1
    mem_limit: 128m
    environment:
      - FLAG=ptzctf{metrics-are-fun}
  app-instance-2:
    <<: *app

networks:
  internal:
