version: '2.2'

services:
    sosuslugi:
        build: service
        restart: always
        ports:
            - 17137:31337
        privileged: true
        stop_grace_period: 3s
        mem_limit: 256M
        memswap_limit: 256M
        cpu_count: 1
        pids_limit: 256
        ulimits: 
            nofile:
                soft: 8192
                hard: 8192
