version: "2.4"
services:
  api:
    build: ./api
    restart: unless-stopped
    environment:
      PORT: 80
      FLAG: ptzctf{fibonacci-http-seems-pointless}
    expose:
      - "80"
    mem_limit: 128M
    pids_limit: 32
    cpus: 2
    stop_signal: SIGINT
  proxy:
    build: ./proxy
    restart: unless-stopped
    ports:
      - "7070:80"
    mem_limit: 256M
    pids_limit: 32
    cpus: 2
    ulimits:
      nofile: 10000
