version: "2.4"

services:
  nginx:
    image: nginx:1.23.2
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/data:ro
    ports:
      - 8384:8384
    restart: unless-stopped
    pids_limit: 64
    cpus: 2
    mem_limit: 256m
